{application,phone_service,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{phone_service_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[content,filog,fs,futil,ivr,ivr_sup,menus,
                        phone_service_app,phone_service_sup,tts,user_db]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
